options:
    # Use namespace functionality to allow for subfolder schema
    namespaces: Yes
    # Relative to this configuration file
    workingpath: "working"
    # Management specific configuration
    management:
        # DB Configuration
        db:
            username: root
            password: test
            ip:       127.0.0.1
            port:     3400
            database: management
    # # Example graylog logging configuration
    # graylog:
    #     hostname:       "127.0.0.1"
    #     port:           80
    #     connection:     "wan"
    #     maxchunksizewan: 42
    #     maxchunksizelan: 1337
    # # parameters will be prefixed to log messages
    #     parameters:
    #         - name:  "hostname"
    #           value: "myhost"
    #
    #         - name:  "env"
    #           value: "live"

# Project Definition
project:
    # Project name - used to identify the project by the cli flags
    # and configure the table's namespace
    name: "animals"
    db:
        username:    root
        password:    test
        ip:          127.0.0.1
        port:        3500
        database:    test
        environment: SANDBOX
    generation:
        templates:
            - file: "yaml.tmpl"
              path: "yaml"
              ext:  "yml"
    # Project Schema Path Configuration
    schema:
        # Relative to the Working Path - otherwise absolute path
        workingrelative: true
        # Paths to the Schema
        namespaces:
            - name:         "Ferrari"
              tableprefix:  "ferrari_"
              schemapath:   "cars/manufacturer/ferrari"

            - name:         "Porsche"
              tableprefix:  "porsche_"
              schemapath:   "cars/manufacturer/porsche"

    # The Project Git configuration
    # git:
    #     # Schema name.  Not currently used
    #     name: "remotetest"
    #     # Git Repo
    #     url:  "http://localhost:3000/sporter/remotetestlocal.git"
    #     # Default Version of the Schema
    #     version: ""
    #     # Subfolders within the Git repo to checkout which contain db schema
    #     folders:
    #         - "test"
